services:
  filegator:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ./frontend:/var/www/filegator/frontend
      - ./backend:/var/www/filegator/backend
